"Resource/UI/SpectatorGUI.res"
{
"SpectatorGUI"
{
"ControlName" "Frame"
"fieldName"  "SpectatorGUI"
"tall"   "480"
"autoResize" "0"
"pinCorner"  "0"
"visible"  "1"
"enabled"  "1"
"tabPosition" "0"
}
"topbar"
{
"ControlName"  "Panel"
"fieldName"  "topbar"
"xpos"   "0"
"ypos"   "0"
"tall"   "40"
"wide"   "640"
"autoResize"  "0"
"pinCorner"  "0"
"visible"  "1"
"enabled"  "1"
"tabPosition"  "0"
}
"Scorebox"
{
"ControlName"     "ImagePanel"
"fieldName"    "Scorebox"
"xpos"     "c-63"
"ypos"     "433" 
"wide"     "126"
"tall"     "35"
"visible"   "1"
"enabled"    "1"
"PaintBackgroundType"   "0"
"fillcolor"    "0 0 0 120" 
}
"Scorebox2"
{
"ControlName"     "ImagePanel"
"fieldName"    "Scorebox2"
"xpos"     "0"
"ypos"     "0"
"wide"     "126"
"tall"     "5"
"visible"   "1"
"enabled"    "1"
"PaintBackgroundType"   "0"
"fillcolor"    "0 0 0 120"
"pin_to_sibling"  "Scorebox"
"pin_corner_to_sibling"  "3"
"pin_to_sibling_corner"  "1"
}
"Scorebox22"
{
"ControlName"     "ImagePanel"
"fieldName"    "Scorebox22"
"xpos"     "0"
"ypos"     "0"
"wide"     "126"
"tall"     "5"
"visible"   "1"
"enabled"    "1"
"PaintBackgroundType"   "0"
"fillcolor"    "TransparentBlack"
"pin_to_sibling"  "Scorebox"
"pin_corner_to_sibling"  "3"
"pin_to_sibling_corner"  "1"
}
"Scorebox3"
{
"ControlName"     "ImagePanel"
"fieldName"    "Scorebox3"
"xpos"     "0"
"ypos"     "0"
"wide"     "126"
"tall"     "5"
"visible"   "1"
"enabled"    "1"
"PaintBackgroundType"   "0"
"fillcolor"    "0 0 0 120"
"pin_to_sibling"  "Scorebox"
"pin_corner_to_sibling"  "1"
"pin_to_sibling_corner"  "3"  
}
"Scorebox33"
{
"ControlName"     "ImagePanel"
"fieldName"    "Scorebox33"
"xpos"     "0"
"ypos"     "0"
"wide"     "126"
"tall"     "5"
"visible"   "1"
"enabled"    "1"
"PaintBackgroundType"   "0"
"fillcolor"    "TransparentBlack"
"pin_to_sibling"  "Scorebox"
"pin_corner_to_sibling"  "1"
"pin_to_sibling_corner"  "3"  
}
"RedLine"
{
"ControlName"     "ImagePanel"
"fieldName"    "RedLine"
"xpos"     "c+63"
"ypos"     "428"
"wide"     "4"
"tall"     "45"
"visible"   "1"
"enabled"    "1"
"PaintBackgroundType"   "0"
"fillcolor"    "255 26 28 255"
}
"BlueLine"
{
"ControlName"     "ImagePanel"
"fieldName"    "RedLine"
"xpos"     "c-66"
"ypos"     "428"
"wide"     "4"
"tall"     "45"
"visible"   "1"
"enabled"    "1"
"PaintBackgroundType"   "0"
"fillcolor"    "128 206 255 255"
}
"bottombarblank"
{
"ControlName"  "Panel"
"fieldName"  "bottombarblank"
"xpos"   "0"
"ypos"   "480"
"tall"   "55"  // this needs to match the size of BottomBar
"wide"   "640"
"autoResize"  "0"
"pinCorner"  "0"
"visible"  "1"
"enabled"  "1"
"tabPosition"  "0"
}
"bottombar2"
{
"ControlName"  "ImagePanel"
"fieldName"  "bottombar2"
"xpos"   "0"
"ypos"   "433"
"zpos"   "-1"
"tall"   "35"
"wide"   "1000"
"autoResize"  "0"
"pinCorner"  "0"
"visible"  "1"
"enabled"  "1"
"tabPosition"  "0"
"fillcolor"  "TransparentBlack"
}
"followinglabel"
{
"ControlName"  "Label"
"fieldName"  "followinglabel"
"xpos"   "c-255"
"ypos"   "0"
"wide"   "350"
"tall"   "25"
"autoResize"  "0"
"pinCorner"  "0"
"visible"  "1"
"enabled"  "1"
"labelText"  "FOLLOWING"
"tabPosition"  "0"
"textAlignment"  "west"
"font"       "toxic_specfont"
"fgcolor_override"  "255 255 255 150"
}
"playerlabel"
{
"ControlName"  "Label"
"fieldName"  "playerlabel"
"xpos"   "c-255"
"ypos"   "12"
"wide"   "350"
"tall"   "25"
"autoResize"  "0"
"pinCorner"  "0"
"visible"  "0"
"enabled"  "1"
"tabPosition"  "0"
"textAlignment"  "west"
"font"       "toxic_specplayer"
}
"scoredivider"
{
"ControlName"  "Label"
"fieldName"  "scoredivider"
"xpos"   "c-5"
"ypos"   "426"
"wide"   "10"
"tall"   "45"
"autoResize"  "0"
"pinCorner"  "0"
"visible"  "1"
"enabled"  "1"
"labelText"  ":"
"tabPosition"  "0"
"textAlignment"  "center"
"font"       "toxic_specscore"
"fgcolor_override"  "255 255 255 255"
}
"CTScoreValue"
{
"ControlName"  "Label"
"fieldName"  "CTScoreValue"
"xpos"   "c-50"
"ypos"   "428"
"wide"   "35"
"tall"   "45"
"autoResize"  "0"
"pinCorner"  "0"
"visible"  "1"
"enabled"  "1"
"labelText"  ""
"textAlignment"  "east"
"dulltext"  "0"
"brighttext"  "0"
"font"       "toxic_specscore"
"fgcolor_override"  "255 255 255 255"
}
"TERScoreValue"
{
"ControlName"  "Label"
"fieldName"  "TERScoreValue"
"xpos"   "c+14"
"ypos"   "428"
"wide"   "35"
"tall"   "45"
"autoResize"  "0"
"pinCorner"  "0"
"visible"  "1"
"enabled"  "1"
"labelText"  ""
"textAlignment"  "west"
"dulltext"  "0"
"brighttext"  "0"
"font"    "toxic_specscore"
"fgcolor_override"  "255 255 255 255"
}
"CTScoreLabel"
{
"ControlName"  "Label"
"fieldName"  "CTScoreLabel"
"xpos"   "c-385"
"ypos"   "440"
"wide"   "280"
"tall"   "20"
"autoResize"  "0"
"pinCorner"  "0"
"visible"  "1"
"enabled"  "1"
"labelText" "COUNTER-TERRORISTS" //%t1name%
"textAlignment"  "east"
"dulltext"  "0"
"brighttext"  "0"
"font"       "toxic_specplayer"
"fgcolor_override"  "255 255 255 255"
}
"TERScoreLabel"
{
"ControlName"  "Label"
"fieldName"  "TERScoreLabel"
"xpos"   "c+107"
"ypos"   "440"
"wide"   "200"
"tall"   "20"
"autoResize"  "0"
"pinCorner"  "0"
"visible"  "1"
"enabled"  "1"
"labelText" "TERRORISTS" //%t2name%
"textAlignment"  "west"
"dulltext"  "0"
"brighttext"  "0"
"font"       "toxic_specplayer"
"fgcolor_override"  "255 255 255 255"
}
"DividerBar"
{
"ControlName"  "ImagePanel"
"fieldName"  "DividerBar"
"xpos"   "r94"
"ypos"   "12"
"wide"   "1"
"tall"   "30"
"autoResize"  "0"
"pinCorner"  "0"
"visible"  "1"
"enabled"  "0"
"tabPosition"  "0"
"fillcolor"  "BorderBright"
"labelText"  ""
"textAlignment"  "center"
}
"timerclock"
{
"ControlName"  "Label"
"fieldName"  "timerclock"
"xpos"   "c"
"ypos"   "39"
"wide"   "16"
"tall"   "19"
"autoResize"  "1"
"pinCorner"  "0"
"visible"  "0"
"enabled"  "0"
"textAlignment"  "center"
"dulltext"  "0"
"brighttext"  "0"
"labelText"  "e"
"font"   "IconsSmall"
}
"timerlabel"
{
"ControlName"  "Label"
"fieldName"  "timerlabel"
"xpos"   "c-50"
"ypos"   "407"
"wide"   "100"
"tall"   "30"
"autoResize"  "0"
"pinCorner"  "0"
"visible"  "1"
"enabled"  "1"
"labelText"  "00:00"
"textAlignment"  "center"
"dulltext"  "0"
"brighttext"  "0"
"font"       "toxic_specfont"
"fgcolor_override"  "255 255 255 255"
}
"infolabel"
{
"ControlName"  "Label"
"fieldName"  "infolabel"
"xpos"   "c+180"
"ypos"   "0"
"wide"   "200"
"tall"   "25"
"autoResize"  "0"
"pinCorner"  "0"
"visible"  "1"
"enabled"  "1"
"labelText"  "INFO"
"tabPosition"  "0"
"textAlignment"  "west"
"font"       "toxic_specfont"
"fgcolor_override"  "255 255 255 150"
}
"extrainfo"
{
"ControlName"  "Label"
"fieldName"  "extrainfo"
"xpos"   "c+180"
"ypos"   "12"
"wide"   "200"
"tall"   "25"
"autoResize"  "0"
"pinCorner"  "0"
"visible"  "1"
"enabled"  "1"
"labelText"  ""
"textAlignment"  "west"
"dulltext"  "0"
"brighttext"  "0"
"font"       "toxic_specfont"
"fgcolor_override"  "255 255 255 255"
}
"titlelabel"
{
"ControlName"  "Label"
"fieldName"  "titlelabel"
"xpos"   "16"
"ypos"   "16"
"wide"   "320"
"tall"   "20"
"autoResize"  "0"
"pinCorner"  "0"
"visible"  "0"
"enabled"  "0"
"font"   "HudNumbersSmall"
"labelText"  ""
"textAlignment"  "west"
"dulltext"  "0"
"brighttext"  "0"
}
}
